### ISSUE TITLE
PoseContext.Isolate throws exceptions when used with net462

### ISSUE THREAD

**Issue by tjrobinson** [tonerdo/pose#1]
I discovered this after using Pose from a test project that's targetting `net462` and it can be reproduced by changing `Pose.Tests.csproj` to use `<TargetFramework>net462</TargetFramework>`.

I'm not sure if this is expected or not but I thought it worth mentioning in case there's a workaround or fix.

```
C:\Code\tonerdo\pose\src\Pose\Pose.csproj : warning NU1701: Package 'Mono.Reflection 1.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'.
This package may not be fully compatible with your project. [C:\Code\tonerdo\pose\test\Pose.Tests\Pose.Tests.csproj]
Build started, please wait...
C:\Code\tonerdo\pose\src\Pose\Pose.csproj : warning NU1701: Package 'Mono.Reflection 1.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'.
This package may not be fully compatible with your project.
Build completed.

Test run for C:\Code\tonerdo\pose\test\Pose.Tests\bin\Debug\net462\Pose.Tests.dll(.NETFramework,Version=v4.6.2)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Failed   Pose.Tests.StubHelperTests.TestGetShimInstance
Error Message:
 Test method Pose.Tests.StubHelperTests.TestGetShimInstance threw exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MethodAccessException: Attempt by method 'DynamicClass.dynamic_Pose.Tests.StubHelperTests+<>c_<T
estGetShimInstance>b__1_1(<>c)' to access method 'DynamicClass.dynamic_Pose.Tests.StubHelperTests+<>c_<TestGetShimInstance>b__1_1(<>c)' failed.
Stack Trace:
    at dynamic_Pose.Tests.StubHelperTests+<>c_<TestGetShimInstance>b__1_1(<>c )
--- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at Pose.PoseContext.Isolate(Action entryPoint, Shim[] shims)
   at Pose.Tests.StubHelperTests.TestGetShimInstance() in C:\Code\tonerdo\pose\test\Pose.Tests\Helpers\StubHelperTests.cs:line 32

Failed   Pose.Tests.StubHelperTests.TestGetShimReplacementMethod
Error Message:
 Test method Pose.Tests.StubHelperTests.TestGetShimReplacementMethod threw exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MethodAccessException: Attempt by method 'DynamicClass.dynamic_Pose.Tests.StubHelperTests+<>c_<T
estGetShimReplacementMethod>b__2_1(<>c)' to access method 'DynamicClass.dynamic_Pose.Tests.StubHelperTests+<>c_<TestGetShimReplacementMethod>b__2_1(<>c)' failed.
Stack Trace:
    at dynamic_Pose.Tests.StubHelperTests+<>c_<TestGetShimReplacementMethod>b__2_1(<>c )
--- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at Pose.PoseContext.Isolate(Action entryPoint, Shim[] shims)
   at Pose.Tests.StubHelperTests.TestGetShimReplacementMethod() in C:\Code\tonerdo\pose\test\Pose.Tests\Helpers\StubHelperTests.cs:line 43

Failed   Pose.Tests.StubHelperTests.TestGetMatchingShimIndex
Error Message:
 Test method Pose.Tests.StubHelperTests.TestGetMatchingShimIndex threw exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MethodAccessException: Attempt by method 'DynamicClass.dynamic_Pose.Tests.StubHelperTests+<>c_<T
estGetMatchingShimIndex>b__3_2(<>c)' to access method 'DynamicClass.dynamic_Pose.Tests.StubHelperTests+<>c_<TestGetMatchingShimIndex>b__3_2(<>c)' failed.
Stack Trace:
    at dynamic_Pose.Tests.StubHelperTests+<>c_<TestGetMatchingShimIndex>b__3_2(<>c )
--- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at Pose.PoseContext.Isolate(Action entryPoint, Shim[] shims)
   at Pose.Tests.StubHelperTests.TestGetMatchingShimIndex() in C:\Code\tonerdo\pose\test\Pose.Tests\Helpers\StubHelperTests.cs:line 59

Failed   Pose.Tests.MethodRewriterTests.TestStaticMethodRewrite
Error Message:
 Test method Pose.Tests.MethodRewriterTests.TestStaticMethodRewrite threw exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MethodAccessException: Attempt by method 'DynamicClass.stub_System.RuntimeMethodHandle_GetFuncti
onPointer(System.RuntimeMethodHandle ByRef, System.RuntimeMethodHandle, System.RuntimeTypeHandle)' to access method 'Pose.Helpers.StubHelper.GetMatchingShimIndex(System.Reflection.MethodInfo, System.Object)' fai
led.
Stack Trace:
    at stub_System.RuntimeMethodHandle_GetFunctionPointer(RuntimeMethodHandle& , RuntimeMethodHandle , RuntimeTypeHandle )
   at dynamic_Pose.Helpers.StubHelper_GetMethodPointer(MethodBase )
--- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at Pose.Tests.MethodRewriterTests.TestStaticMethodRewrite() in C:\Code\tonerdo\pose\test\Pose.Tests\IL\MethodRewriterTests.cs:line 23

Failed   Pose.Tests.MethodRewriterTests.TestInstanceMethodRewrite
Error Message:
 Test method Pose.Tests.MethodRewriterTests.TestInstanceMethodRewrite threw exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.FieldAccessException: Attempt by method 'DynamicClass.dynamic_System.Collections.Generic.List`1[
System.String]_Add(System.Collections.Generic.List`1<System.String>, System.String)' to access field 'System.Collections.Generic.List`1<System.__Canon>._size' failed.
Stack Trace:
    at dynamic_System.Collections.Generic.List`1[System.String]_Add(List`1 , String )
--- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at Pose.Tests.MethodRewriterTests.TestInstanceMethodRewrite() in C:\Code\tonerdo\pose\test\Pose.Tests\IL\MethodRewriterTests.cs:line 36


Total tests: 27. Passed: 22. Failed: 5. Skipped: 0.
Test Run Failed.
Test execution time: 1.1821 Seconds
```

```
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by tonerdo** [comment]
@tjrobinson thanks I'd look into this. Are you able to still use the library?

**Comment by tjrobinson** [comment]
Thanks. I can't use it at the moment but am in the process of porting my code over to support `netstandard2.0` so that I can.

**Comment by tonerdo** [comment]
@tjrobinson This issue has been fixed. Will merge into master and create a new release later today
